### ISSUE TITLE
Error While Install On kali linux

### ISSUE THREAD

**Issue by 0xAwali** [bytebutcher/decoder-plus-plus#27] opened 2021-01-06 08:27 UTC
Firstly I Installed Decoder++ using pip3
pip3 install decoder-plus-plus

![Screenshot_2021-01-06_08-27-24](https://user-images.githubusercontent.com/54332136/103746211-625b2400-5009-11eb-8474-b19119e3f85e.png)

So Until Now Everything Is OK

But When Running dpp With
 python3 /path/to/dpp/runner.py
I Got This Error 

![Screenshot_2021-01-06_08-28-51](https://user-images.githubusercontent.com/54332136/103746388-b403ae80-5009-11eb-8525-201f89a36e7e.png)

So Please Help Me To Solve This

**Comment by bytebutcher** [comment] 2021-01-07 00:04
Hi 0xAwali,
thanks for reporting this issue. I can confirm that there is currently a problem running ```Decoder++``` in the latest kali version.
It looks like i need to update the PyQt5 package to the latest version (current: 5.14, latest: 5.15). 

In the meantime you should be able to fix this error by reinstalling PyQt5:
```
$ sudo pip3 uninstall PyQt5  
$ sudo pip3 install PyQt5
```

Please let me know if this fixed the problem for you.

**Comment by bytebutcher** [comment] 2021-01-07 01:16
I've updated the source code and uploaded a new version to pypi.
```
$ sudo pip3 uninstall decoder-plus-plus
$ sudo pip3 install decoder-plus-plus
```

**Comment by 0xAwali** [comment] 2021-01-07 02:08
Actually , I Got A new Error Before The Output As You Can See In The Image

![Screenshot_2021-01-07_02-10-06](https://user-images.githubusercontent.com/54332136/103842175-f1198080-509d-11eb-8106-980f58598efe.png)

**Comment by bytebutcher** [comment] 2021-01-07 15:35
Thanks again. I was able to replicate this error. It happens when runner.py is called directly without dpp being installed via setup.py or pip. 

The error should be fixed now. You can get the updated version either by ```git pull``` or by reinstalling decoder-plus-plus via pip3.

For the sake of documentation, here's the complete error message:
```
dpp/runner.py:234: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if value is "True" or value is "False":
dpp/runner.py:234: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if value is "True" or value is "False":
dpp/runner.py:235: SyntaxWarning: "is" with a literal. Did you mean "=="?
  value = value is "True"
Traceback (most recent call last):
  File "dpp/runner.py", line 34, in <module>
    from dpp.core.argparse.ordered_multi_args import OrderedMultiArgs
ModuleNotFoundError: No module named 'dpp'
```

**Closed as completed** 2021-01-12 14:32 UTC

**Comment by bytebutcher** [comment] 2021-01-12 14:34
I'll close this issue for now. Please let me know if the error still persists.
